apiVersion: v1
kind: Service
metadata:
  name: {{ include "hoppscotch.fullname" . }}
  labels:
{{ include "hoppscotch.labels" . | indent 4 }}
{{ include "hoppscotch.extra_labels" . | indent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http
      port: {{ .Values.service.containerPort }}
      protocol: TCP
  selector:
    app.kubernetes.io/name: {{ include "hoppscotch.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
