version: "3.7"

x-uffizzi:
  ingress:
    service: web
    port: 3000

services:
  web:
    image: ${HOPPSCOTCH_IMAGE}
    ports:
      - "3000:3000"
    environment:
      HOST: 0.0.0.0
    command: "npm run dev"
